version: "2"

services:
  app:
    image: pageturner/builder:latest
    cpu_shares: 100
    mem_limit: 268435456
    ports:
      - 80:80
    environment:
      APP_ENV:
      WEBHOOK_SECRET:
      MONITORED_BRANCH:
      S3_BUCKET_NAME:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_KEY:
      AWS_REGION:
      REDIS_URL:
      RABBITMQ_URL:
