version: "2"

services:
  builder:
    build: .
    ports:
      - 8080:80
    links:
      - redis
    volumes:
      - sites:/sites
    environment:
      - WEBHOOK_SECRET
      - MONITORED_BRANCH

  redis:
    image: redis:3.2

  sites:
    image: nginx:stable
    ports:
      - 8090:80
    volumes_from:
      - builder
    volumes:
      - sites:/usr/share/nginx/html:ro

volumes:
  sites:
